"use client";

import React, { useState, useMemo, useEffect } from "react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { BookOpen, Search, X } from "lucide-react";

interface GlossaryTerm {
  term: string;
  definition: string;
  category: "Technical Analysis" | "Fundamental Analysis" | "Indian Markets" | "Tax & Regulations" | "General Trading";
}

const glossaryData: GlossaryTerm[] = [
  {
    term: "MA (Moving Average)",
    definition: "A widely used indicator in technical analysis that helps smooth out price action by filtering out the 'noise' from random short-term price fluctuations. It is a trend-following indicator based on past prices.",
    category: "Technical Analysis"
  },
  {
    term: "RSI (Relative Strength Index)",
    definition: "A momentum oscillator that measures the speed and change of price movements. Traditionally, an RSI reading above 70 indicates an overbought condition, while a reading below 30 indicates an oversold condition.",
    category: "Technical Analysis"
  },
  {
    term: "Beta",
    definition: "A measure of a stock's volatility relative to the overall market. A beta of 1 means the stock moves with the market; greater than 1 means it is more volatile, and less than 1 means it is less volatile.",
    category: "Fundamental Analysis"
  },
  {
    term: "Alpha",
    definition: "The abnormal rate of return on an investment or portfolio in excess of what would be predicted by an equilibrium model like CAPM. Simply put, it represents the edge or 'active return' generated by a strategy.",
    category: "Fundamental Analysis"
  },
  {
    term: "SEBI",
    definition: "Securities and Exchange Board of India. The regulatory body for the securities and commodity market in India under the jurisdiction of the Ministry of Finance.",
    category: "Tax & Regulations"
  },
  {
    term: "NSE",
    definition: "National Stock Exchange of India. The leading democratic marketplace and electronic stock exchange located in Mumbai, India.",
    category: "Indian Markets"
  },
  {
    term: "BSE",
    definition: "Bombay Stock Exchange. Asia's oldest stock exchange, established in 1875, based in Dalal Street, Mumbai.",
    category: "Indian Markets"
  },
  {
    term: "STT (Securities Transaction Tax)",
    definition: "A direct tax levied on every purchase and sale of equities, derivatives, and equity-oriented mutual funds listed on a recognized stock exchange in India.",
    category: "Tax & Regulations"
  },
  {
    term: "TCS (Tax Collected at Source)",
    definition: "In trading context, specifically relevant for foreign equity investments. Under Liberalised Remittance Scheme (LRS), remittances/investments in foreign stocks above ₹7 Lakhs attract a 20% TCS.",
    category: "Tax & Regulations"
  },
  {
    term: "LTCG (Long Term Capital Gains)",
    definition: "The profit earned on selling an asset/stock held for more than 1 year. For Indian equity, gains exceeding ₹1.25 Lakh per year are taxed at 12.5%.",
    category: "Tax & Regulations"
  },
  {
    term: "STCG (Short Term Capital Gains)",
    definition: "The profit earned on selling an asset/stock held for less than 1 year. For Indian equity, it is taxed at a flat rate of 20%.",
    category: "Tax & Regulations"
  },
  {
    term: "OHLC",
    definition: "Stands for Open, High, Low, and Close. A type of bar or candlestick chart that displays these four critical price data points for a chosen timeframe.",
    category: "Technical Analysis"
  },
  {
    term: "F&O (Futures & Options)",
    definition: "Derivatives segments where contracts derive value from an underlying asset. Features high leverage, specified expiry dates, and significant risks.",
    category: "General Trading"
  },
  {
    term: "Brokerage",
    definition: "The fee or commission charged by a stockbroker to an investor for executing buy or sell orders on their behalf.",
    category: "General Trading"
  },
  {
    term: "Nifty 50",
    definition: "The benchmark stock market index for the Indian equity market, representing the weighted average of 50 of the largest Indian companies listed on the National Stock Exchange.",
    category: "Indian Markets"
  },
  {
    term: "S&P 500",
    definition: "A stock market index tracking the stock performance of 500 of the largest companies listed on stock exchanges in the United States.",
    category: "General Trading"
  }
];

export default function GlossaryPage() {
  const [mounted, setMounted] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);

  // Avoid hydration layout shifts by waiting for client-side mount
  useEffect(() => {
    setMounted(true);
  }, []);

  const categories = useMemo(() => {
    const list = glossaryData.map((item) => item.category);
    return Array.from(new Set(list));
  }, []);

  const filteredGlossary = useMemo(() => {
    return glossaryData.filter((item) => {
      const matchesSearch =
        item.term.toLowerCase().includes(searchQuery.toLowerCase()) ||
        item.definition.toLowerCase().includes(searchQuery.toLowerCase());
      const matchesCategory = selectedCategory ? item.category === selectedCategory : true;
      return matchesSearch && matchesCategory;
    });
  }, [searchQuery, selectedCategory]);

  if (!mounted) {
    return <div className="min-h-screen bg-gray-950" />;
  }

  return (
    <div className="min-h-screen bg-gray-950 text-gray-100 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-5xl mx-auto space-y-8">
        
        {/* Header section */}
        <div className="text-center space-y-3">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-sm">
            <BookOpen className="w-4 h-4" /> Market Knowledge Base
          </div>
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Financial & Trading Glossary
          </h1>
          <p className="text-gray-400 max-w-2xl mx-auto">
            Demystifying trading terminologies, regulatory parameters, technical indicators, and taxing frameworks for Indian and Global instruments.
          </p>
        </div>

        {/* Filters Controls */}
        <div className="space-y-4 bg-gray-900 border border-gray-800 p-6 rounded-xl">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500 w-5 h-5" />
            <Input
              type="text"
              placeholder="Search concepts, acronyms, or taxation definitions..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-10 bg-gray-950 border-gray-800 focus-visible:ring-emerald-500 text-gray-100"
            />
            {searchQuery && (
              <button
                onClick={() => setSearchQuery("")}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-200"
              >
                <X className="w-4 h-4" />
              </button>
            )}
          </div>

          {/* Category Pills */}
          <div className="flex flex-wrap gap-2 items-center pt-2">
            <span className="text-xs font-semibold uppercase tracking-wider text-gray-500 mr-2">
              Filter by:
            </span>
            <Button
              variant={selectedCategory === null ? "default" : "outline"}
              size="sm"
              onClick={() => setSelectedCategory(null)}
              className={`text-xs ${
                selectedCategory === null
                  ? "bg-emerald-500 text-gray-950 hover:bg-emerald-600"
                  : "border-gray-800 hover:bg-gray-800 text-gray-300"
              }`}
            >
              All Terms
            </Button>
            {categories.map((category) => (
              <Button
                key={category}
                variant={selectedCategory === category ? "default" : "outline"}
                size="sm"
                onClick={() => setSelectedCategory(category)}
                className={`text-xs ${
                  selectedCategory === category
                    ? "bg-emerald-500 text-gray-950 hover:bg-emerald-600"
                    : "border-gray-800 hover:bg-gray-800 text-gray-300"
              }`}
              >
                {category}
              </Button>
            ))}
          </div>
        </div>

        {/* Results Grid */}
        {filteredGlossary.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {filteredGlossary.map((item) => (
              <Card
                key={item.term}
                className="bg-gray-900 border-gray-800 transition-all hover:border-gray-700 flex flex-col justify-between"
              >
                <CardHeader className="pb-2">
                  <div className="flex justify-between items-start gap-4">
                    <CardTitle className="text-lg font-bold text-emerald-400 tracking-tight">
                      {item.term}
                    </CardTitle>
                    <span className="text-[10px] font-medium tracking-wide bg-gray-800 text-gray-400 border border-gray-700/50 px-2 py-0.5 rounded-md shrink-0">
                      {item.category}
                    </span>
                  </div>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-gray-300 leading-relaxed">
                    {item.definition}
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>
        ) : (
          <div className="text-center py-16 border border-dashed border-gray-800 rounded-xl bg-gray-900/30">
            <p className="text-gray-400 text-sm">No terms match your filtering criteria.</p>
            <Button
              variant="link"
              onClick={() => {
                setSearchQuery("");
                setSelectedCategory(null);
              }}
              className="text-emerald-400 p-0 text-sm h-auto mt-1"
            >
              Reset all filters
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}